apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerAuthorization
metadata:
  name: my-authz-policies
  namespace: azure-iot-operations
spec:
  listenerRef:
    - rag-listener # change to match your listener name as needed
  authorizationPolicies:
    enableCache: false
    rules:
      - principals:
          attributes:
            - group: dapr-workload
        brokerResources:
          - method: Connect
          - method: Publish
            topics:
              - "$services/statestore/#"
          - method: Subscribe
            topics:
              - "clients/{principal.clientId}/services/statestore/#"