name: Main Branch CI
on: 
  push:
    branches: 
      - main
  
jobs:
  Build-Code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.11.0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.11.0
      with:
        useConfigFile: true
    - name: Create git tag
      run: |
        git tag ${{ env.GitVersion_MajorMinorPatch }}
      if: github.ref == 'refs/heads/main'
    - name: Push git tag
      run: git push origin ${{ env.GitVersion_MajorMinorPatch }}
      if: github.ref == 'refs/heads/main'
